// Convert public/mumei-mascot.png into ASCII art and write the result
// into server/lib/mascot-ascii.ts as a frozen string constant. Run
// manually after replacing the mascot artwork; the output is committed
// so runtime needs no PNG decoder.
//
//   npx tsx scripts/generate-mascot-ascii.ts
//
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { PNG } from 'pngjs'

const HERE = path.resolve(import.meta.dirname, '..')
const SRC = path.join(HERE, 'public/mumei-mascot.png')
const OUT = path.join(HERE, 'server/lib/mascot-ascii.ts')

const TARGET_W = 36
const RAMP = ' .:-=+*#%@'

const png = PNG.sync.read(readFileSync(SRC))
const W = png.width
const H = png.height
// Terminal cells are roughly 2× taller than wide; halve vertical samples
// so the rendered mascot stays in proportion.
const TARGET_H = Math.max(1, Math.round((H / W) * TARGET_W * 0.5))

const lines: string[] = []
for (let y = 0; y < TARGET_H; y++) {
  let line = ''
  for (let x = 0; x < TARGET_W; x++) {
    const sx = Math.floor((x / TARGET_W) * W)
    const sy = Math.floor((y / TARGET_H) * H)
    const idx = (sy * W + sx) * 4
    const r = png.data[idx] ?? 0
    const g = png.data[idx + 1] ?? 0
    const b = png.data[idx + 2] ?? 0
    const a = png.data[idx + 3] ?? 0
    if (a < 128) {
      line += ' '
      continue
    }
    const lum = 0.299 * r + 0.587 * g + 0.114 * b
    const ci = Math.min(
      RAMP.length - 1,
      Math.max(0, Math.floor((1 - lum / 255) * (RAMP.length - 1))),
    )
    line += RAMP[ci]
  }
  lines.push(line.replace(/\s+$/, ''))
}

const trimmed: string[] = []
let started = false
for (const l of lines) {
  if (!started && l.trim() === '') continue
  started = true
  trimmed.push(l)
}
while (trimmed.length > 0 && trimmed[trimmed.length - 1]?.trim() === '') trimmed.pop()

const escaped = trimmed.map((l) => l.replace(/\\/g, '\\\\').replace(/`/g, '\\`'))
const body = `// Generated by scripts/generate-mascot-ascii.ts from public/mumei-mascot.png.
// Do not edit by hand — re-run the script if the mascot artwork changes.

export const MASCOT_ASCII = \`
${escaped.join('\n')}
\`
`

writeFileSync(OUT, body)
process.stdout.write(`wrote ${OUT} (${trimmed.length} lines)\n`)
